### ISSUE TITLE
size issue

### ISSUE THREAD

**Issue by ghost** [klezVirus/CheeseTools#1] opened 2021-10-18 19:52 UTC
I like the project but exes are too big for execute assembly on cobaltstrike for example.
i was obliged to upload the full binary on the target (NOT OPSEC SAFE).

**Comment by klezVirus** [comment] 2021-10-18 22:20
Hi @fendi1989, that's interesting indeed. I think the problem is caused by costura, did you encounter the same issue with all of them out with one in particular?

**Comment by ghost** [comment] 2021-10-18 22:23
Cheesesql is too big , rdp is ok , and ill test Ps and Dcom tomorrow.

**Comment by klezVirus** [comment] 2022-02-05 10:45
Hi fendi, thanks a lot for your help here. 
Upon further consideration, as the size limitation is a CobaltStrike problem, and it's not a functional issue related the CheeseSQL or any other tools in this repo (and indeed it doesn't show up in other C2, like Covenant), I'm closing this issue.
However, even if not a priority, I'll surely go and check if we can find a way to reduce the size of `CheeseSQL` as soon as I have time to do so. 
Feel free to reopen/comment is there is anything else you want to add to the conversation.

**Closed as completed by klezVirus** 2022-02-05 10:45 UTC
Labels: good first issue
